- name: Setup Docker and Nginx on EC2 instance
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Ensure /usr/share/nginx/html directory exists
      file:
        path: /usr/share/nginx/html
        state: directory
        mode: '0755'

    - name: Deploy Nginx container
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - /usr/share/nginx/html:/usr/share/nginx/html  # Mounting host folder to the container

    - name: Add puppy HTML page to Nginx
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <html>
          <head><title>Puppy Page</title></head>
          <body>
            <h1>Welcome to the Puppy Page!</h1>
            <img src="https://place-puppy.com/200x200" alt="puppy">
          </body>
          </html>

    - name: Restart Nginx container to apply changes
      docker_container:
        name: nginx
        state: restarted