- name: Setup Docker and Nginx on EC2 instance
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Ensure /usr/share/nginx/html directory exists
      file:
        path: /usr/share/nginx/html
        state: directory
        mode: '0755'

    - name: Deploy Nginx container
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
            - "80:80" 
            - "443:80"
        volumes:
          - /usr/share/nginx/html:/usr/share/nginx/html  # Mounting host folder to the container

    - name: Add puppy HTML page to Nginx
      copy:
        src: ../app/index.html
        dest: /usr/share/nginx/html/index.html
        
    - name: Add puppy image to Nginx     
      copy:
        src: ../app/puppy.png
        dest: /usr/share/nginx/html/puppy.png

    - name: Stop Nginx container
      docker_container:
        name: nginx
        state: stopped

    - name: Start Nginx container
      docker_container:
        name: nginx
        state: started
