name: Deploy to AWS

on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      TF_VAR_ansible_key_name: ansible-key

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Import existing key pair if it exists
        run: 
          set +e
          terraform import aws_key_pair.deployer ansible-key || echo "Key does not exist yet or already managed"
          set -e
          
      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get public IP from Terraform
        id: get_ip
        run: |
          echo "Fetching EC2 IP..."
          IP=$(terraform output -raw public_ip)
          echo "ip=${IP}" >> "$GITHUB_OUTPUT"


      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible

      - name: Add private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | sed 's/\\n/\n/g' > ~/id_rsa
          chmod 600  ~/id_rsa

      - name: Set up Ansible inventory
        run: |
          echo "[web]" > inventory.ini
          echo "${{ steps.get_ip.outputs.ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/id_rsa" >> inventory.ini
        env:
          IP: ${{ steps.terraform.outputs.public_ip }}


      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini ansible/deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
